# Generated by Django 2.1.8 on 2019-05-16 02:29

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_window', models.CharField(choices=[('06:00 AM - 08:00 AM', '06:00 AM - 08:00 AM'), ('08:00 AM - 10:00 AM', '08:00 AM - 10:00 AM'), ('10:00 AM - Noon', '10:00 AM - Noon'), ('02:00 PM - 04:00 PM', '02:00 PM - 04:00 PM'), ('04:00 PM - 06:00 PM', '04:00 PM - 06:00 PM'), ('06:00 PM - 08:00 PM', '06:00 PM - 08:00 PM')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_status', models.CharField(choices=[('WDTN', 'Waiting for Destination Definition'), ('WDRV', 'Waiting for assigning a driver'), ('PSCH', 'Pickup Scheduled'), ('TRAN', 'In Transit'), ('DLVR', 'Delivered')], max_length=4)),
                ('agreed_time_window', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport_order.Time_Window')),
            ],
        ),
        migrations.CreateModel(
            name='Week_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('transport_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_order.Transport_Order')),
            ],
        ),
        migrations.AddField(
            model_name='transport_order',
            name='agreed_weekday',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekday_assigned', to='transport_order.Week_Day'),
        ),
        migrations.AddField(
            model_name='transport_order',
            name='destination',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_assigned', to='address.Address'),
        ),
        migrations.AddField(
            model_name='transport_order',
            name='donated_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.Donation'),
        ),
        migrations.AddField(
            model_name='transport_order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport_order',
            name='origin',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
        migrations.AddField(
            model_name='time_window',
            name='week_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_order.Week_Day'),
        ),
    ]
