# Generated by Django 2.1.8 on 2019-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_order',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transport_order',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
