# Generated by Django 2.1.8 on 2019-05-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_order', '0002_auto_20190517_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='time_window',
            name='week_day',
        ),
        migrations.RemoveField(
            model_name='week_day',
            name='transport_order',
        ),
        migrations.RemoveField(
            model_name='transport_order',
            name='agreed_weekday',
        ),
        migrations.AlterField(
            model_name='transport_order',
            name='agreed_time_window',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_available_time', to='transport_order.AvailableTime'),
        ),
        migrations.DeleteModel(
            name='Time_Window',
        ),
        migrations.DeleteModel(
            name='Week_Day',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='transport_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_order.Transport_Order'),
        ),
    ]
