# Generated by Django 2.1.8 on 2019-05-12 22:32

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('dimension', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('WC', 'Waiting for claim'), ('CL', 'Claimed'), ('ST', 'In Stock'), ('AD', 'Allocated for donation'), ('DT', 'Donated'), ('LS', 'Lost / Stolen'), ('DE', 'Damaged / Expired')], default='WC', max_length=2)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donation.Donee'),
        ),
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.Institution'),
        ),
    ]
