# Generated by Django 2.1.8 on 2019-05-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20190515_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donee',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
